server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    info.path: /info/**
    info.serviceId: info-service
    info.retryable: true

    user.path: /user/**
    user.serviceId: user-service
    user.retryable: true

    order.path: /order/**
    order.serviceId: order-service
    order.retryable: true

    res.path: /res/**
    res.serviceId: res-service
    res.retryable: true
